Links:
    https://towardsdatascience.com/loess-373d43b03564 <--- implementacion de python
    
    https://numpy.org/doc/stable/reference/index.html <--- numpy doc

In [4]:
import numpy as np

In [16]:
testData1 = np.random.randint(4, size=10)
testData2 = np.random.randint(3, size=10)

In [5]:
def tricubica (x):
    y = np.zeros_like(x) #Return an array of zeros with the same shape and type as a given array
    idx = (x >= 0) & (x < 1) #da un array de true o false dependiendo si el elemento en la posicion cumplia la condicion
    y[idx] = np.power(1.0 - np.power(x[idx], 3), 3)
    return y

In [18]:
tricubica(testData1)

array([1, 0, 1, 0, 1, 0, 0, 1, 1, 1])

Upon initialization, both input arrays must be normalized to avoid problems of loss of significance (aka, catastrophic cancellation). This is done quite simply with a rescaling to the interval between zero and one.

In [6]:
def normalizar_array(array):
    min_val = np.min(array)
    max_val = np.max(array)
    return (array - min_val) / (max_val - min_val), min_val, max_val

In [21]:
normData = normalizar_array(testData1)
print(testData1)
print(normData)

[0 3 0 3 0 2 1 0 0 0]
(array([0.        , 1.        , 0.        , 1.        , 0.        ,
       0.66666667, 0.33333333, 0.        , 0.        , 0.        ]), 0, 3)


In [7]:
def obtenerPesos(distancias, min_range):
    max_dist = np.max(distancias[min_range])
    pesos = tricubica(distancias[min_range] / max_dist)

Hasta aca llegue, tampoco quiero meterle mucho si no les gusta la idea de basarse en el articulo :p

In [8]:
def get_min_range(distancias, q):
    min_idx = np.argmin(distancias)
    n = len(distancias)
    if min_idx == 0:
        return np.arange(0, q)
    if min_idx == n-1:
        return np.arange(n - q, n)
    
    min_range = [min_idx]    
    while len(min_range) < q:
        i0 = min_range[0]
        i1 = min_range[-1]
        if i0 == 0:
            min_range.append(i1 + 1)
        elif i1 == n-1:
            min_range.insert(0, i0 - 1)
        elif distancias[i0-1] < distancias[i1+1]:
            min_range.insert(0, i0 - 1)
        else:
            min_range.append(i1 + 1)
    return np.array(min_range)
    

In [ ]:

def estimate(x, q, degree=1):
    n_x = normalizar_array(x)
    distances = np.abs(self.n_xx - n_x)
    min_range = get_min_range(distances, window)
    weights = get_weights(distances, min_range)

    wm = np.multiply(np.eye(window), weights)
    xm = np.ones((window, degree + 1))

    xp = np.array([[math.pow(n_x, p)] for p in range(degree + 1)])
    for i in range(1, degree + 1):
        xm[:, i] = np.power(self.n_xx[min_range], i)

    ym = self.n_yy[min_range]
    xmt_wm = np.transpose(xm) @ wm
    beta = np.linalg.pinv(xmt_wm @ xm) @ xmt_wm @ ym
    y = (beta @ xp)[0]
   
    return self.denormalize_y(y)
